/* DO NOT EDIT THIS FILE - it is machine generated
 * JNI的实现类的头文件
 * */
#include <jni.h>
#include "GameService.cpp"
/* Header for class com_game_sdk_QFGame */

#ifndef _Included_com_game_sdk_jni_QFGame
#define _Included_com_game_sdk_jni_QFGame
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_game_sdk_QFGame
 * Method:    InitQFServer
 * Signature: ()V
 * 初始化
 */
JNIEXPORT jint JNICALL Java_com_game_sdk_jni_QFGame_InitQFServer
        (JNIEnv *jniEnv, jclass jk) {
    return initService(jniEnv, jk);
}

/*
 * Class:     com_game_sdk_QFGame
 * Method:    setQFNum
 * Signature: (F)V
 * 动态设置加速阈值
 */
JNIEXPORT void JNICALL Java_com_game_sdk_jni_QFGame_setQFNum
        (JNIEnv *jniEnv, jclass jk, jfloat num) {
    setNum(jniEnv, jk, num);
} ;

/*
 * Class:     com_game_sdk_QFGame
 * Method:    QFAddTime
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_game_sdk_jni_QFGame_QFAddTime
        (JNIEnv *, jclass) {
//    后面新增的
    noEngine();
} ;

/*
 * Class:     com_game_sdk_QFGame
 * Method:    test
 * Signature: (F)V
 */
JNIEXPORT jstring JNICALL Java_com_game_sdk_jni_QFGame_test
        (JNIEnv *env, jclass jc, jstring msg) {
    returnTest(env, jc);
    return msg;
} ;


#ifdef __cplusplus
}
#endif
#endif
